#!/usr/bin/env python3
"""
LAPSlock brand asset generator.

Source geometry lives here, not in a design file. Every asset is reproducible from
this script, which means the icon can be regenerated at any size without hunting for
a .sketch nobody can open.

Marks in this file:
  * "keyhole" - keycap + keyhole. Shipped briefly, then replaced. The name reads as a
                keyboard key (LAPS lock / Caps Lock), so the icon is an artifact the
                buyer touches all day, with the credential meaning in the keyhole.
  * "tread"   - realistic tire-tread ring + keyhole, full circle. The PitLAPS
                heritage direction. Realism comes from pattern structure, not
                texture: three ribs split by circumferential grooves, staggered
                angled lateral slots leaning opposite directions (directional
                chevron), pitch lengths jittered like real tires vary pitch. All
                flat geometry, so it stays inside the no-photo-texture constraint
                and regenerates at any size.
  * "skid"    - same tread pattern as two broken arcs with blunt ends and fading
                block clusters, after the family's original mock.
  * Append "_light" to tread/skid for the inverted palette (navy mark on light
                field, the mock's own colorway).
  * "padlock" - kept only for comparison. Failed the 29x29 test and the "could be
                any security app" test.

Earlier geometric-tread attempts, recorded so nobody retries them:
  sparse chunky blocks read as a poker chip, sheared blocks as a camera shutter,
  herringbone chevron blocks as the recycle glyph, staggered block rows turned to
  noise below 87 px. The fix was inverting the figure: a mostly-solid band with
  thin grooves CUT INTO it reads as tire; sparse blocks with big gaps never did.

Deliberately NOT in the icon:
  * the wordmark. "LAPSlock" stacked over two lines is unreadable at 60x60 on a home
    screen and worse at 29x29 in Settings. The wordmark is a separate asset for the
    site and docs, generated further down.
  * keycap + tread + keyhole together. Three metaphors in one square is one too
    many; every mark here picks two.

Usage:  python3 render-icon.py [outdir]
Deps:   Pillow only (pip3 install pillow)
"""

import math
import os
import random
import sys

from PIL import Image, ImageDraw, ImageFont

# ---------------------------------------------------------------- palette

NAVY = (0x16, 0x23, 0x3A)      # field, and the lock glyph on the keycap
STEEL = (0x4A, 0x6E, 0x96)     # keycap side walls, LAPS in the wordmark
CAP = (0xEE, 0xF3, 0xF8)       # keycap top face, tread + keyhole on navy field
INK = (0x1A, 0x1A, 0x1A)       # "lock" in the wordmark
PAPER = (0xFF, 0xFF, 0xFF)

# Supersample factor. PIL has no antialiased vector fill, so everything is drawn
# large and downsampled with LANCZOS.
SS = 4

# NOTE 2026-08-29: shipping assets (appiconset, Entra logo) are now generated by
# texturize-icon.py, which composes the photoreal tread over this file's geometry.
# HISTORICAL. The clean keycap is no longer what ships: the shipping icon is the
# PHOTOREAL tread produced by texturize-icon.py (SHIP_BASE there is authoritative).
# This constant now only affects the single-mark emitters below, which main() no
# longer calls. See design/icons/README.md.
# The emitters below remain for the clean marks; RECOMMENDED_MARK only affects
# what THIS script writes when run directly.
RECOMMENDED_MARK = "keyhole"

# Pitch jitter seed. Fixed so renders are byte-stable run to run; change it only if
# you want a different (still reproducible) block rhythm.
TREAD_SEED = 31

# First bold sans found wins. Linux first, then macOS.
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
]


def _font(size):
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    raise SystemExit("no bold sans found; add a .ttf path to FONT_CANDIDATES")


def _rr(draw, box, radius, fill):
    draw.rounded_rectangle(box, radius=radius, fill=fill)


def _pol(cx, cy, r, deg):
    a = math.radians(deg)
    return (cx + r * math.cos(a), cy + r * math.sin(a))


def _band(draw, cx, cy, r_a, r_b, a0, a1, fill, step=1.5):
    """Filled annulus sector from angle a0 to a1 (degrees), radius r_a to r_b."""
    n = max(2, int((a1 - a0) / step))
    outer = [_pol(cx, cy, r_b, a0 + (a1 - a0) * k / n) for k in range(n + 1)]
    inner = [_pol(cx, cy, r_a, a0 + (a1 - a0) * k / n) for k in range(n + 1)]
    draw.polygon(outer + inner[::-1], fill=fill)


def draw_keyhole(draw, cx, cy, w, color):
    """A keyhole: circle over a tapered slot.

    One shape with one hole is the whole idea. It survives 29x29, where a padlock
    with a separate shackle, body and keyhole turns to mush, and it carries over the
    keyhole motif from the previous icon so the brand does not restart from zero.

    Vertical extent is cy - 0.5w to cy + 1.30w; visual center sits at cy + 0.4w.
    """
    r = w * 0.5
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=color)
    slot_top = cy + r * 0.35
    slot_bot = cy + w * 1.30
    draw.polygon([(cx - r * 0.46, slot_top), (cx + r * 0.46, slot_top),
                  (cx + r * 0.86, slot_bot), (cx - r * 0.86, slot_bot)], fill=color)
    draw.rounded_rectangle([cx - r * 0.86, slot_bot - r * 0.35,
                            cx + r * 0.86, slot_bot], radius=r * 0.18, fill=color)


def draw_tread(draw, cx, cy, S, ring, bg, arcs, fade):
    """Directional tire footprint bent into ring arcs, as flat geometry.

    Radial layout, inner to outer: shoulder rib (43% of band) | groove |
    center rib | groove | shoulder rib. Lateral slots lean +5.5 deg on the inner
    shoulder and -5.5 on the outer, forming the directional chevron that says
    "tire"; the center rib carries finer sipes offset by half a pitch, and the
    two shoulders are staggered a quarter pitch, like real pitch sequencing.

    Pitch lengths are jittered (seeded) then rescaled to close each arc exactly,
    so a full ring has no seam and arc ends land evenly.
    """
    r_mid = S * 0.306
    h0 = S * 0.066            # band half-width
    g_w = S * 0.0105          # circumferential groove width
    rng = random.Random(TREAD_SEED)
    r_in, r_out = r_mid - h0, r_mid + h0
    band = 2 * h0
    g1 = r_in + band * 0.43
    g2 = r_in + band * 0.615
    pitch = 13.0

    for a_start, a_end in arcs:
        span = a_end - a_start
        # A closed ring wraps: no end insets anywhere, or 12 o'clock shows a seam
        closed = abs(span - 360.0) < 1e-6
        _band(draw, cx, cy, r_in, r_out, a_start, a_end, ring)

        if fade:  # trailing tread-block clusters past each blunt end
            for tip, s in ((a_start, -1), (a_end, +1)):
                gap = 3.4
                for hf, wf in ((0.80, 3.4), (0.55, 2.3), (0.32, 1.4)):
                    c = tip + s * gap
                    _band(draw, cx, cy, r_mid - h0 * hf, r_mid + h0 * hf,
                          c - wf / 2, c + wf / 2, ring)
                    gap += wf + 2.6

        groove_inset = 0.0 if closed else 0.5
        for gr in (g1, g2):
            _band(draw, cx, cy, gr - g_w / 2, gr + g_w / 2,
                  a_start + groove_inset, a_end - groove_inset, bg)

        # jittered pitches, rescaled to close the arc exactly (no 12 o'clock seam)
        margin = 0.0 if closed else (2.0 if fade else 0.0)
        usable = span - 2 * margin
        incs = []
        while sum(incs) < usable:
            incs.append(pitch * (1.0 + rng.uniform(-0.12, 0.12)))
        scale = usable / sum(incs)
        pos, marks = a_start + margin, []
        for inc in incs:
            marks.append(pos)
            pos += inc * scale

        rows = [(r_in, g1 - g_w / 2, +5.5, 3.0, 0.00),   # inner shoulder
                (g1 + g_w / 2, g2 - g_w / 2, +2.0, 1.6, 0.50),   # center sipes
                (g2 + g_w / 2, r_out, -5.5, 3.0, 0.25)]  # outer shoulder
        for r_a, r_b, lean, wdeg, phase in rows:
            for base in marks:
                c = base + pitch * phase
                # on a closed ring every slot is valid; angles wrap through trig
                if not closed and not (a_start + margin < c < a_end - margin):
                    continue
                draw.polygon([_pol(cx, cy, r_a, c - wdeg / 2 - lean / 2),
                              _pol(cx, cy, r_a, c + wdeg / 2 - lean / 2),
                              _pol(cx, cy, r_b, c + wdeg / 2 + lean / 2),
                              _pol(cx, cy, r_b, c - wdeg / 2 + lean / 2)], fill=bg)


def draw_padlock(draw, cx, cy, w, color, face=None):
    """Alternate mark: a padlock. Kept for comparison against the keyhole."""
    face = face or CAP
    body_w = w
    body_h = w * 0.72
    body_top = cy - body_h * 0.10
    _rr(draw, [cx - body_w / 2, body_top, cx + body_w / 2, body_top + body_h],
        radius=w * 0.15, fill=color)

    sh_out = w * 0.62
    stroke = w * 0.145
    sh_cy = body_top
    draw.arc([cx - sh_out / 2, sh_cy - sh_out / 2, cx + sh_out / 2, sh_cy + sh_out / 2],
             start=180, end=360, fill=color, width=int(stroke))
    leg_x = sh_out / 2 - stroke / 2
    for sx in (-leg_x, leg_x):
        draw.rectangle([cx + sx - stroke / 2, sh_cy,
                        cx + sx + stroke / 2, body_top + 1], fill=color)

    kh = w * 0.20
    kcy = body_top + body_h * 0.40
    draw.ellipse([cx - kh / 2, kcy - kh / 2, cx + kh / 2, kcy + kh / 2], fill=face)
    draw.polygon([(cx - kh * 0.28, kcy), (cx + kh * 0.28, kcy),
                  (cx + kh * 0.15, kcy + kh * 1.2),
                  (cx - kh * 0.15, kcy + kh * 1.2)], fill=face)


def render_icon(size=1024, mark="keyhole"):
    """The app icon. No alpha channel: the App Store rejects icons with one.

    Keycap marks: the keycap is drawn with an asymmetric bevel, thin at the top and
    thick at the bottom, which is what makes it read as a key seen slightly from
    above rather than as a rounded square badge. A uniform border reads as a frame,
    not a keycap.

    Tread/skid marks: ring outer diameter is 0.744 of the canvas, inside the iOS
    squircle mask's safe area.
    """
    S = size * SS
    base = mark.replace("_light", "")
    light = mark.endswith("_light")

    if base in ("tread", "skid"):
        field, ring = (CAP, NAVY) if light else (NAVY, CAP)
        img = Image.new("RGB", (S, S), field)
        d = ImageDraw.Draw(img)
        if base == "tread":
            arcs, fade = [(-90.0, 270.0)], False
        else:
            arcs, fade = [(-140.0, 15.0), (40.0, 190.0)], True
        draw_tread(d, S / 2, S / 2, S, ring, field, arcs, fade)
        kw = S * 0.180
        # draw_keyhole's visual center is cy + 0.4w; offset so it centers on canvas
        draw_keyhole(d, S / 2, S / 2 - kw * 0.40, kw, ring)
        return img.resize((size, size), Image.LANCZOS)

    img = Image.new("RGB", (S, S), NAVY)
    d = ImageDraw.Draw(img)
    cap_w = S * 0.640
    x0 = (S - cap_w) / 2
    y0 = (S - cap_w) / 2 - cap_w * 0.020
    _rr(d, [x0, y0, x0 + cap_w, y0 + cap_w], radius=cap_w * 0.190, fill=STEEL)

    side = cap_w * 0.070
    top_in = cap_w * 0.055
    bot_in = cap_w * 0.150
    fx0, fy0 = x0 + side, y0 + top_in
    fx1, fy1 = x0 + cap_w - side, y0 + cap_w - bot_in
    _rr(d, [fx0, fy0, fx1, fy1], radius=cap_w * 0.130, fill=CAP)

    face_cx = (fx0 + fx1) / 2
    face_cy = (fy0 + fy1) / 2
    if base == "keyhole":
        draw_keyhole(d, face_cx, face_cy - cap_w * 0.055, cap_w * 0.205, NAVY)
    else:
        draw_padlock(d, face_cx, face_cy - cap_w * 0.010, cap_w * 0.300, NAVY)

    return img.resize((size, size), Image.LANCZOS)


def render_wordmark(width=1600, stacked=False):
    """Wordmark for the site, README, and App Store screenshots.

    LAPS in steel, lock in ink, matching the concept the family sketched.
    """
    if stacked:
        W, H = width, int(width * 0.62)
    else:
        W, H = width, int(width * 0.30)
    S = (W * 2, H * 2)
    img = Image.new("RGB", S, PAPER)
    d = ImageDraw.Draw(img)

    size = int(S[1] * (0.42 if stacked else 0.55))
    font = _font(size)

    def measure(t):
        b = d.textbbox((0, 0), t, font=font)
        return b[2] - b[0], b[3] - b[1], b

    if stacked:
        w1, h1, b1 = measure("LAPS")
        w2, h2, b2 = measure("lock")
        total_h = h1 + h2 + size * 0.06
        top = (S[1] - total_h) / 2
        d.text(((S[0] - w1) / 2 - b1[0], top - b1[1]), "LAPS", font=font, fill=STEEL)
        d.text(((S[0] - w2) / 2 - b2[0], top + h1 + size * 0.06 - b2[1]),
               "lock", font=font, fill=INK)
    else:
        w1, h1, b1 = measure("LAPS")
        w2, h2, b2 = measure("lock")
        total = w1 + w2
        left = (S[0] - total) / 2
        base = (S[1] - h1) / 2
        d.text((left - b1[0], base - b1[1]), "LAPS", font=font, fill=STEEL)
        d.text((left + w1 - b2[0], base - b1[1]), "lock", font=font, fill=INK)

    return img.resize((W, H), Image.LANCZOS)


CONTENTS_JSON = """{
  "images" : [
    {
      "filename" : "AppIcon-LAPSlock-1024.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
"""

PROOF_SIZES = [180, 120, 87, 60, 29]


def emit_appiconset(out, mark=RECOMMENDED_MARK):
    """Single-size asset catalog. Xcode 14+ generates every derived size from the
    1024 itself, so shipping one file is correct and one fewer thing to keep in sync."""
    d = os.path.join(out, "AppIcon.appiconset")
    os.makedirs(d, exist_ok=True)
    render_icon(1024, mark).save(os.path.join(d, "AppIcon-LAPSlock-1024.png"))
    with open(os.path.join(d, "Contents.json"), "w") as f:
        f.write(CONTENTS_JSON)


def emit_entra_logo(out, mark=RECOMMENDED_MARK):
    """Entra app registration logo: 215x215 PNG, must stay under 100 KB.

    This is the image on the consent screen, which is the moment the product lives or
    dies. An admin granting read access to every local admin password in their tenant
    should not be looking at a default placeholder."""
    render_icon(215, mark).save(os.path.join(out, "entra-logo-215.png"), optimize=True)


def emit_proof_strip(out, mark):
    """Not shipped. Exists so a human can judge the icon at the sizes iOS actually
    renders it, instead of only at 1024."""
    strip_w = sum(PROOF_SIZES) + 44 * len(PROOF_SIZES)
    strip = Image.new("RGB", (strip_w, 230), (0xF5, 0xF5, 0xF7))
    x = 22
    for s in PROOF_SIZES:
        strip.paste(render_icon(s, mark), (x, (230 - s) // 2))
        x += s + 44
    strip.save(os.path.join(out, f"proof-strip-{mark}.png"))


def emit_comparison_sheet(out, marks):
    """All candidate marks on one sheet, one row per mark, columns at iOS sizes.
    This is the image decisions get made from."""
    pad = 36
    row_h = max(PROOF_SIZES) + pad
    W = sum(PROOF_SIZES) + pad * (len(PROOF_SIZES) + 1)
    H = row_h * len(marks) + pad
    sheet = Image.new("RGB", (W, H), (0xF5, 0xF5, 0xF7))
    y = pad
    for m in marks:
        x = pad
        for s in PROOF_SIZES:
            sheet.paste(render_icon(s, m), (x, y + (max(PROOF_SIZES) - s) // 2))
            x += s + pad
        y += row_h
    sheet.save(os.path.join(out, "comparison-sheet.png"))


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(out, exist_ok=True)

    candidates = ("keyhole", "tread", "skid", "tread_light", "skid_light")
    for mark in candidates:
        render_icon(1024, mark).save(os.path.join(out, f"AppIcon-LAPSlock-{mark}-1024.png"))
        emit_proof_strip(out, mark)
    emit_comparison_sheet(out, candidates)

    # NOTE: this script deliberately does NOT emit AppIcon.appiconset or the Entra
    # logo any more. The shipping icon is the PHOTOREAL tread, and it comes from
    # texturize-icon.py, which imports the geometry from this file and adds the print
    # treatment. Emitting here as well meant `python3 render-icon.py` would silently
    # overwrite the shipping asset catalog with the clean keycap.
    #
    # This file is now for exploring candidates and generating the wordmarks.
    # To produce shipping assets:  python3 texturize-icon.py <outdir> --synth

    render_wordmark(1600, stacked=False).save(os.path.join(out, "wordmark-inline.png"))
    render_wordmark(1200, stacked=True).save(os.path.join(out, "wordmark-stacked.png"))
    print("wrote candidate sheets and wordmarks to", out)
    print("shipping assets come from texturize-icon.py, not this script")


if __name__ == "__main__":
    main()
